### ISSUE TITLE
Custom Session ID

### ISSUE THREAD

**Issue by hishayness** [hapijs/yar#104]
Hello!

Looking through the source code, I don't see a way to provide a custom session id. I was looking into layering multiple security hashes to the id to allow some extended functionalities (eg. dropping certain sets of session ids from persistent store). I was wondering if this was perhaps somewhere down in the roadmap or not something that yar was intended to ever support out of the box?

**Comment by mark-bradshaw** [comment]
PRs gratefully accepted. :)

**Comment by sirgallifrey** [comment]
I think I can help with that, can I work on this issue?

**Comment by mark-bradshaw** [comment]
Of course @sirgallifrey

**Comment by sirgallifrey** [comment]
almost done, but there is a issue that bothers me. If we let the dev assign any ID that he wants, that will allow duplicated ids... Is that something that I have to prevent or it will be the developer's responsibility?

**Comment by mark-bradshaw** [comment]
Dev responsibility I'd say.  They might do it on purpose.

**Comment by mark-bradshaw** [comment]
Thanks Adilson.  On first glance it looks good.  I'll do some more checking on it later.

**Comment by mark-bradshaw** [comment]
Implemented in #106.  Published as v8.1.0
