### ISSUE TITLE
No session in auth scheme

### ISSUE THREAD

**Issue by thesbros** [hapijs/yar#111]
When trying to access a session variable with `req.yar.get` in an auth scheme, the session store is empty.

Is this intended behavior? I need to access the session in my authentication method to check if the request has a valid access token.

**Comment by mark-bradshaw** [comment]
Can you post a simplified example of what you're doing?

**Comment by thesbros** [comment]
Something seems to have changed and it works now. I'll reopen the issue if it breaks again. Sorry for the inconvenience.
