### ISSUE TITLE
Flash messages not deleted when added in context through the onPreResponse extension point

### ISSUE THREAD

**Issue by acmoune** [hapijs/yar#113]
I am creating flash messages from some handlers using this code:

```javascript
request.yar.flash('success', 'Resource created !');
```

Then in my handlebars layout, I add this:

`{{#if flash.success}}<div class="alert alert-success">{{flash.success}}</div>{{/if}}`

What is missing is the code that stores the flash messages in the flash template variable.

If for example I want to display the previous flash success message in the '/' route, I get it working when I do this directly in the route handler:

```javascript
const flashMessages = {
    success: request.yar.flash('success'),
};

return reply.view('index', { flash: flashMessages });
```
The problems start when I want to do it in `onPreResponse` extension point. See code below:

```javascript
server.ext('onPreResponse', (request, reply) => {
      const res = request.response;

      if (res.variety === 'view') {
        if (!res.source.context) res.source.context = {};

        const flashMessages = {
          success: request.yar.flash('success')
        };

        res.source.context.flash = flashMessages;
      }

      reply.continue();
});
```
So in my handler I can just do this `reply.view('index')`, and the flash template variable will be automatically set in the `onPreResponse` extension point. 

The problem is that the flash message are not deleted, they are accumulated. The first time it outputs 'Resource created !', the second time it outputs 'Resource created !Resource created !' and so on.

I am unable to find what is wrong here. The only difference between the two methods is the time when I add the flash messages in context. I the first method, the working one, I do it right in the route handler; in the second method, I do it in the `onPreResponse` extension point. What is **yar** doing differently between those two moments ?

Please help

**Comment by mtharrison** [comment]
I suspect what is happening here is that your `onPreResponse` which flushes the flash from your session is being executed after the `onPreResponse` logic in yar which serializes your session into the cookie in the response. You might try stating that your extension has a `before` dependency on yar:

```js
server.ext({
    type: 'onPreResponse',
    method: (request, reply) => {

        const res = request.response;

        if (res.variety === 'view') {
            if (!res.source.context) res.source.context = {};

            debugger;

            const flashMessages = {
                success: request.yar.flash('success')
            };

            res.source.context.flash = flashMessages;
        }

        reply.continue();
    },
    options: {
        before: ['yar']
    }
});
```
Another point to note is that if the route that sets your flash also renders a view then it will be flushed on that route rather than the next HTTP request, which may or may not be what you want but you should be aware of it. Typically I've seen flash messages set before a redirect to another route.

**Comment by acmoune** [comment]
OK, so if I got you right, I have to fetch the flash value before Yar's `onPreResponse` handler is executed, it is that handler that will notice that the value has been fetched and then empty the cookie.

I just updated my `onPreResponse` extension point with the before option, and now it works.

Many thanks @mtharrison
