### ISSUE TITLE
why the _store is empty each request

### ISSUE THREAD

**Issue by DyncKevin** [hapijs/yar#119]
hi, sorry to bother you.
just a small question, maybe it's my problem but i can't find out way to solve it.

in each request i call request.yar.set(userId, {token: value}); to store user info, and i can  get token value in this request. but, next time  request with same api, i can't get userId's token value, i console out request.yar, the _store is empty.
at first i thought it's because of the difference of request.yar.id, so i use the same request.yar.id by customSessionIDGenerator, the yar._store is also empty.

my question is that: in first request i set userId value, how to get userId value in next request.

my manifest is like this:

manifest = {
    server: {
        port: envKey('port'),
        routes: {
            cors: true
        },
        router: {
            stripTrailingSlash: true
        },
        cache: [
            {
                name: 'redisCache',
                engine: require('catbox-redis'),
                host: '127.0.0.1',
                partition: 'cache',
                password: '123456'
            }
        ]
    },
    register: {
        plugins: [
            {
                plugin: 'yar', // this is for session
                options: {
                    storeBlank: false,
                    maxCookieSize: 1024,
                    errorOnCacheNotReady: true,
                    name: 'session',
                    cache: {
                        cache: 'redisCache',
                        expiresIn: 600*1000,
                        segment: 'session'
                    },
                    cookieOptions: {
                        password: 'querasdf123456789012345678901234567890qwerasdf',
                        clearInvalid: true,
                        ignoreErrors: true,
                        isSameSite: 'Strict',
                        isHttpOnly: true,
                        isSecure: false,
                        ttl: 120000
                    },
                    customSessionIDGenerator: function(){
                        return "123456";
                    }
                }
            }
        ],
        options: {
            once: true
        }
    }
};

**Comment by andrewnaeve** [comment]
I am also calling request.yar.set('hi', {key: 'hello'}) and getting undefined calling request.yar.get('hi') on the next request. Hapi v 16.1.0.

**Comment by Marsup** [comment]
Can you both check that the cookie is actually set in the browser ?

**Comment by DyncKevin** [comment]
@Marsup thank you very much, it is the cooking setting problem.

**Comment by DyncKevin** [comment]
another question, if my configure above is using catbox-redis or redis, after yar.set, why can't i get the value by redis-client. when I enter redis cmd like "keys userId" or "get userId", I got nothing.

**Comment by Marsup** [comment]
catbox has absolutely nothing to do with yar.

**Comment by DyncKevin** [comment]
hi ， it seems that chrome do not allow get and send cookie, i am using axios to handle http

**Comment by hueniverse** [comment]
Please open a new issue instead of reopening this one. Also, better to ask the last question in hapijs/discuss.
