### ISSUE TITLE
Using hapi's server.decorate could be dangerous.

### ISSUE THREAD

**Issue by twiggy** [hapijs/yar#120]
I had an issue with another piece of software that resulted in yar loading the wrong session data into another users request. Very weird, but with lots of debugging it came down to hapi's decorate function that sets up the request.hapi object. Part of me thinks this might be a hapi design issue, but honestly not sure.

In yar's index.js around line 55 it uses decorate.

`
 server.decorate('request', 'yar', getState, {
        apply: true
    });
`

I was using an apm tool that decorated this function wrong, effectively not passing {apply:true} in. So the fourth argument wasn't being set.

You can reproduce this "bug" by just excluding apply:true.

Now fire up an app and create a session. Then open another browser/machine so you don't have the cookies and look at your request.yar ... it will be the first browser session object. Which is super weird and obviously break security.

I can totally understand to just blame it on this third party software, but i wonder if its worth just doing some thing like 
`
 if ( !request.yar || request.yar == null ){ request.yar= {} );

Thanks for the consideration and the project!

**Comment by hueniverse** [comment]
What do you mean decorated this function wrong? You can't decorate a method twice.
