### ISSUE TITLE
Falsy values are converted to null

### ISSUE THREAD

**Issue by simplesmiler** [hapijs/yar#121]
When you set a falsy value (`0`, `''`, `false`, etc.), you will get `null` instead of the value.

Example:
```js
request.yar.set('visits', 1);
console.log(request.yar.get('visits')); // logs 1

request.yar.set('visits', 0);
console.log(request.yar.get('visits')); // logs null
```

Version: 9.0.1
Happens in this line https://github.com/hapijs/yar/blob/v9.0.1/lib/index.js#L155

If this is not an expected behavior, ping me and I will make a PR.

**Comment by hueniverse** [comment]
Seems like a bug. PR would be great.
