### ISSUE TITLE
Delete a specific user's session 

### ISSUE THREAD

**Issue by tomnocon** [hapijs/yar#123]
I'm trying to implement the [Back-Channel Logout](https://openid.net/specs/openid-connect-backchannel-1_0.html)  from the **OpenId Connect** specification. There is a case when the OpenID Provider (OP) want to delete session in the Relying Party (RP) for a specific user. Is it possible to delete a specific user's session?

To accomplish the above requirement, a method is needed for deleting a specific session. I've found a workaround solution but I think that it is not a good idea.

```javascript
 const cache = server._core.caches.get('_default');
 cache.client.drop({id: sessionId, segment: '!yar'})
```

I would be good to do it directly in the **yar** object.

**Comment by tomnocon** [comment]
Yes, that's exactly what I mean. I'll create a PR.

**Comment by tomnocon** [comment]
Hello, @hueniverse. I'm also prepared backward compatibility branch that I was forked from the `v8.1.2` tag. I need the yar with this feature in v9 and v8 version. Can you create a branch from the `v8.1.2` version? So then I'll be able to create a pull request for previous version. Thanks!

**Comment by dchrzascik** [comment]
Hi @hueniverse, would it be possible to do as @tomnocon suggests? Our issue depends on resultion of this ticket and we would love to see it merged and closed. Thanks!
