### ISSUE TITLE
Flash messages don't clear

### ISSUE THREAD

**Issue by ThisIsMissEm** [hapijs/yar#54]
I've got code in my server such as:

```
plugin.ext('onPreResponse', function (request, reply) {
      if (request.response.variety === 'view') {
        request.response.source.context = Hoek.applyToDefaults({
          flash: request.session.flash()
        }, request.response.source.context);
      }

      reply();
    });
```

And then in a route `POST /foo`, I'm calling: 

```
request.session.flash('success', 'Item saved successfully');
reply.redirect('/');
```

I'd expect that if I reload '/', that the I wouldn't see the `success` message again. I'd also expect that if I navigate to another page, I'd not have the `flash` value still there. That is, I'd expect request.session.flash() to only return the values stored once, and then invalidate them.

However, this doesn't seem to be the case.

**Comment by nathanbuchar** [comment]
This is literally my exact same problem! Thank you for posting your solution :)
