### ISSUE TITLE
Disable Yar for specific routes

### ISSUE THREAD

**Issue by micahlmartin** [hapijs/yar#68]
I'm looking for a way to prevent yar from assigning a session cookie on  specific routes. Particularly on routes that serve my static assets. Is there a way to disable it by passing in options to the plugin?

**Comment by micahlmartin** [comment]
Added a PR here that solves this issue for me. #69

**Comment by mark-bradshaw** [comment]
Thanks Micah.  I'll close this and take a look at the PR.
