### ISSUE TITLE
Issue using yar with hapi for session management

### ISSUE THREAD

**Issue by vkumara** [hapijs/yar#70]
I've just tested the node.js (v 0.10.36), npm (2.4.1). Checking only for session handling here

package.json dependencies: 
```json
 "dependencies": {
    "hapi": "^8.1.0",
    "yar": "^3.0.3"
  }
```
app.js code 

```js
var Hapi = require('hapi');

var server = new Hapi.Server();
var options = {
         cookieOptions: {
                password: 'password',
                isSecure: false
                          }
};

server.register(
{
  register: require('yar'),
   options: options
}, function (err) {

   if (err) {
   console.log('Error occured in loading', err);}
}
);

server.connection({ port: 3000 });
server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        console.log("======= session ==============", request.session);
      }
});

server.start(function () {
    console.log('Options: ', options);
    console.log('Server running at:', server.info.uri);
});
```

When this runs it prints session as null. Please let me know anything wrong with the code or anything missing? Looks like it doesn't initialize the session for request? No errors present either.

**Comment by arb** [comment]
You need to set session via `request.session.set()` See the documentation [here](https://github.com/hapijs/yar#methods). Yar just provides a methods for managing encrypted encrpyed cookie values. The developer is still responsible for setting them.

**Comment by vkumara** [comment]
Hi, Thanks for the reply.

Yes setting the values are fine, but at the time of the code for log statement above the session in the request is null.

But as the documentation says "yar adds the session property to every request object and initializes the session.id on the first request from each browser", shouldn't it be initializing the session first in order to set the id? Are you saying that the session initialization also need to be done by the developer?

**Comment by arb** [comment]
Change your startup code to look like this:

```js
server.register({
  register: require('yar'),
   options: options
}, function (err) {

   if (err) {
   console.log('Error occured in loading', err);}

   server.start(function () {
       console.log('Options: ', options);
       console.log('Server running at:', server.info.uri);
   });
});
```

My thought is you're starting the server before `yar` has finished loading itself. When I made the above change, I get information logged about `request.session`.
