### ISSUE TITLE
Cluster session concurrent write

### ISSUE THREAD

**Issue by Selvatico** [hapijs/yar#73]
Hello to all,

So problem is next  - we have several workers in cluster. 2 of them receive requests almost at the same time  - each of them read session storage (MongoDB in our case). In parallel they are finishing their work and save all values of from session 
```
request.session._store
```
 to cache storage. And one of them override value of another, because both of them doesn't see changes of another and dump all data to storage. I'm wondering if exist some technics to avoid such behavior using **yar** ?  Because from my point of view  - we should implement in yar some atomic updates, but it should be implemented in **catbox** adapters too, which requires too much changes in core of Hapi.

**Comment by PavelPolyakov** [comment]
@OmniJeff 
Hi, what is your view on the parallel writes?
How this should be done according to the architecture of the application ? Or how could we avoid this?

**Comment by OmniJeff** [comment]
This would be a problem for catbox, which is what yar uses as its persistence layer. yar has little control over how catbox caches data.

**Comment by OmniJeff** [comment]
Will not change catbox behavior. Good explanation here: https://github.com/hapijs/catbox-mongodb/issues/13#issuecomment-107678848
