### ISSUE TITLE
session duration

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/yar#77]
@OmniJeff Any reservations to a PR making the session duration configurable?

**Comment by hueniverse** [comment]
You can already set how long the cookie should last and how long the session information is saved in the cache. What else do you need?

**Comment by mark-bradshaw** [comment]
I didn't see that in the docs.  Am I missing it, or do the docs need
updating.

**Comment by hueniverse** [comment]
No idea. You can see it in the code...

**Comment by mark-bradshaw** [comment]
So looking at the code, I'd use the cookie options config section to set a duration.  The other duration is for server storage, so that's not necessarily what I want.  I'll do some experimentation, and maybe send in a PR to update docs if I'm right.

**Comment by hueniverse** [comment]
Sounds good.
