### ISSUE TITLE
Usage of ^

### ISSUE THREAD

**Issue by hueniverse** [hapijs/yar#87]
Don't use ^ in package.json unless the code will not work with n.x.x instead. Basically, ^ means you rely on a change in a minor revision. It is not correct to just use it to force the latest and greatest if you don't require it.

**Comment by mark-bradshaw** [comment]
Can you explain a bit more about why you want this change?  I don't see the benefits outweighing the costs.

**Comment by hueniverse** [comment]
It's how we do things. When you use ^ you are making a statement that any version prior will not work. That's not true for most of these. You shouldn't move versions up just because you feel like it or happened to set whatever version was latest at the random time you published.

**Comment by mark-bradshaw** [comment]
OK.  I've updated the package.json file and it'll go out that way on the next release.
