### ISSUE TITLE
Session never expires

### ISSUE THREAD

**Issue by krasimirkostadinow** [hapijs/yar#92]
Hello,

I'm facing issue related to the session time out. When a request with cookie which is already expired is sent, the server responds well and it seems there is no server-side check if the cookie is expired.
I know the browsers check the expiration date and the max age parameter and if the cookie is not valid, it will not be added to the headers, but it is strange to me the server has no validation on that.

**Comment by gergoerdosi** [comment]
![adele-hello-screengrab](https://cloud.githubusercontent.com/assets/371149/12419113/421d2cba-beb4-11e5-99db-de15de7766a2.jpg)

**Comment by mark-bradshaw** [comment]
We've just relied on the client to expire the cookies, knowing that session replay was always a possibility.  We could encode the expiration in the body of the cookie, since it's encrypted, and do additional checks there.  Let me consider that.

**Comment by mark-bradshaw** [comment]
What if we added a new config option called `enforceCookieExpiration` that encoded an expiration date in the cookie data, and verified that the cookie was still in force before using it as session data.  A down side is that by inflating the cookie data you get less data storage using that mechanism before you have to fall back to server caching.  I'm inclined to add it, but leave it off by default.

**Comment by mark-bradshaw** [comment]
Going to leave this open for PRs.

**Comment by ittus** [comment]
It seems that IE doesn't support some input types, like 'date'

Reference:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/The_native_form_widgets#Date_and_time_picker

**Comment by mark-bradshaw** [comment]
@ittus It feels like you've wandered into the wrong issue by mistake.  Did you perhaps mean to post this on another repo in another issue?

**Comment by hueniverse** [comment]
This is not a security module, but just an easy way to keep temporary state. If you need more advance features, this module is probably too limited.
