### ISSUE TITLE
request.yar.get

### ISSUE THREAD

**Issue by xycloud** [hapijs/yar#95]
TypeError: Uncaught error: request.yar.get is not a function

**Comment by mark-bradshaw** [comment]
Can you provide more context or access to a repo where I can see the issue in action?

**Comment by devmarco** [comment]
Hey, this method is not working for me. Maybe I am doing something wrong.

I have defined the cookie in a route, for example '/auth'
```
req.yar.set('token', token);
```

and then, in another route, before render the page, I am trying to get the token with the get method
```
req.yar.get('token');
```

but this is not working, always I got undefined. I can see the session stored in my cookie, but I have no idea why the 'get' is not working. Can you help me with that?

**Comment by mark-bradshaw** [comment]
Can you please post your code somewhere I can review?

**Comment by devmarco** [comment]
Auth route:

```
const auth = {
	method: 'POST',
	path: '/auth',
	config: {
		validate: {
			options: {
				abortEarly: false,
			},
		},
		handler: function(req, reply) {
			//Example
                        req.yar.set('example', req.payload.token);
			reply();
		},
	},
};
```

Index route:

```
const route = {
	method: 'GET',
	path: '/{path*}',
	config: {
		state: {
			parse: true,
			failAction: 'error',
		},
		handler: function(req, reply) {
			console.log(req.yar.get('example'));
			return reply();
		},
	},
};

module.exports = route;

```

I access the page for example 'localhost:8080', and the I catch the index route, inside the page a make a post request to the 'auth' route, and then I set the session. After that If I try to refresh the browser, I access in another tab, the get method of yar, always return undefined.

**Comment by devmarco** [comment]
Hey @mark-bradshaw 
Any updates?

**Comment by mark-bradshaw** [comment]
I haven't yet.  Perhaps tonight.

**Comment by mark-bradshaw** [comment]
@devmarco I ran through your code tonight.  What you are doing looks fine to me, and that sort of workflow should be good.  My best guess is that perhaps you have `isSecure: true` in your yar config, which insists that you be using `https` to connect.  Try setting that to false and retrying.  If it works, you'll want to make use of configuration options to turn isSecure off when developing locally, but make sure it gets turned back on in production.

**Comment by devmarco** [comment]
Hey @mark-bradshaw, the ```isSecure``` property is false, could you please test it with the property ```isSecure``` equal false?

```
storeBlank: false,
cookieOptions: {
     isSecure: false,
},
```

**Comment by devmarco** [comment]
Hey @mark-bradshaw, my mistake here, you can keep this issue closed.

Thank you for your help.
